import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import FooterLogin from "../../components/Footer/FooterLogin";
import HeaderLogin from "../../components/Header/HeaderLogin";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Digital Money House",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderLogin />
        {children}
        <FooterLogin />
        </body>
    </html>
  );
}
